CREATE TABLE abilidades (
    id_ability INT PRIMARY KEY,
    nome_abilidade VARCHAR(30),
    descricao_abilidade VARCHAR(255)
);

CREATE TABLE moves (
    id_move INT PRIMARY KEY,
    nome_move VARCHAR(30),
    str_move INT,
    acc_move INT,
    tipo_move VARCHAR(15),
    categoria_move CHAR
);

CREATE TABLE pokemon_data (
    id_data INT PRIMARY KEY,
    nome_pokemon VARCHAR(25),
    descricao_pokemon VARCHAR(255),
    imagem_pokemon VARCHAR(255),
    icone_pokemon VARCHAR(255),
    tipo1_pokemon VARCHAR(15),
    tipo2_pokemon VARCHAR(15)
);

CREATE TABLE pokemon_abilities (
    id_pokemon INT,
    id_ability INT,
    PRIMARY KEY (id_pokemon, id_ability),
    FOREIGN KEY (id_pokemon) REFERENCES pokemon_data(id_data),
    FOREIGN KEY (id_ability) REFERENCES abilidades(id_ability)
);

CREATE TABLE pokemon_moves (
    id_pokemon INT,
    id_move INT,
    PRIMARY KEY (id_pokemon, id_move),
    FOREIGN KEY (id_pokemon) REFERENCES pokemon_data(id_data),
    FOREIGN KEY (id_move) REFERENCES moves(id_move)
);


INSERT INTO abilidades (id_ability, nome_abilidade, descricao_abilidade)
VALUES
    (1, 'Overgrow', 'Powers up Grass-type moves when HP is low.'),
    (2, 'Blaze', 'Powers up Fire-type moves when HP is low.'),
    (3, 'Torrent', 'Powers up Water-type moves when HP is low.'),
    (4, 'Chlorophyll', 'Boosts the Pokémon''s Speed in harsh sunlight.'),
    (5, 'Rain Dish', 'The Pokémon gradually recovers HP in rain.'),
    (6, 'Sand Veil', 'Boosts the Pokémon''s Evasion in a sandstorm.'),
    (7, 'Rock Head', 'Protects the Pokémon from recoil damage.'),
    (8, 'Levitate', 'Gives full immunity to Ground-type moves.'),
    (9, 'Static', 'May cause paralysis if touched.'),
    (10, 'Lightning Rod', 'Draws in all Electric-type moves to up Sp. Attack.'),
    (11, 'Pressure', 'The Pokémon raises the foe''s PP usage.'),
    (12, 'Speed Boost', 'The Pokémon''s Speed stat is gradually boosted.'),
    (13, 'Sturdy', 'The Pokémon is protected against one-hit KO attacks.'),
    (14, 'Synchronize', 'Passes on a burn, poison, or paralysis to the foe.'),
    (15, 'Thick Fat', 'The Pokémon is protected by a layer of thick fat that halves the damage from Fire- and Ice-type moves.'),
    (16, 'Huge Power', 'Raises the Pokémon''s Attack stat.'),
    (17, 'Pure Power', 'Raises the Pokémon''s Attack stat.'),
    (18, 'Trace', 'The Pokémon copies the foe''s Ability.'),
    (19, 'Arena Trap', 'Prevents the foe from fleeing.'),
    (20, 'Magnet Pull', 'Prevents Steel-type Pokémon from escaping.'),
    (21, 'Soundproof', 'The Pokémon is protected from sound-based moves.'),
    (22, 'Rain Forecast', 'The Pokémon transforms with the weather to change its type to Water.'),
    (23, 'Shadow Tag', 'Prevents the foe from escaping.'),
    (24, 'Rough Skin', 'May cause injury when the Pokémon makes contact.'),
    (25, 'Wonder Guard', 'Only supereffective moves will hit.'),
    (26, 'Levitate', 'Gives full immunity to Ground-type moves.'),
    (27, 'Effect Spore', 'May cause paralysis, poison, or sleep if touched.'),
    (28, 'Synchronize', 'Passes on U problems to the foe.'),
    (29, 'Clear Body', 'Prevents other Pokémon from lowering its stats.'),
    (30, 'Liquid Ooze', 'Draining moves used on the Pokémon deal damage.'),
    (31, 'White Smoke', 'Prevents the Pokémon''s stats from being lowered.'),
    (32, 'Pure Power', 'Raises the Pokémon''s Attack stat.'),
    (33, 'Shell Armor', 'The Pokémon is protected against critical hits.'),
    (34, 'Air Lock', 'Eliminates the effects of weather.'),
    (35, 'Tangled Feet', 'Raises evasion if the Pokémon is confused.'),
    (36, 'Motor Drive', 'Raises Speed if hit by an Electric-type move.'),
    (37, 'Rivalry', 'Boosts the Attack stat if the foe is of the same gender.'),
    (38, 'Intimidate', 'Lowers the foe''s Attack stat.'),
    (39, 'Shadow Tag', 'Prevents the foe from escaping.'),
    (40, 'Wonder Guard', 'Only supereffective moves will hit.'),
    (41, 'Synchronize', 'Passes on U problems to the foe.'),
    (42, 'Keen Eye', 'Prevents other Pokémon from lowering its Accuracy.'),
    (43, 'Illuminate', 'Raises the likelihood of meeting wild Pokémon.'),
    (44, 'Pickup', 'The Pokémon may pick up items.'),
    (45, 'Vital Spirit', 'Prevents the Pokémon from falling asleep.'),
    (46, 'Anger Point', 'Maxes the Attack stat after the Pokémon takes a critical hit.'),
    (47, 'Rivalry', 'Boosts the Attack stat if the foe is of the same gender.'),
    (48, 'Unburden', 'Raises Speed if a held item is used.'),
    (49, 'Heatproof', 'The heatproof body of the Pokémon halves the damage from Fire-type moves that hit it.'),
    (50, 'Dry Skin', 'Reduces HP if it is hot. Water restores HP.'),
    (51, 'Solar Power', 'Powers up the Pokémon in harsh sunlight, but HP decreases.'),
    (52, 'Leaf Guard', 'Prevents U conditions in harsh sunlight.'),
    (53, 'Klutz', 'The Pokémon can''t use any held items.'),
    (54, 'Mold Breaker', 'Moves can be used regardless of Abilities.'),
    (55, 'Super Luck', 'The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.'),
    (56, 'Aftermath', 'Damages the foe landing the finishing hit.'),
    (57, 'Anticipation', 'The Pokémon can sense an opposing Pokémon''s dangerous moves.'),
    (58, 'Forewarn', 'The Pokémon can sense a foe''s dangerous moves.'),
    (59, 'Unaware', 'Ignores any changes in Ability by the foe.'),
    (60, 'Tinted Lens', 'Powers up "not very effective" moves.'),
    (61, 'Filter', 'Powers down the foe''s super-effective moves.'),
    (62, 'Slow Start', 'For five turns, the user''s Attack and Speed stats are halved.'),
    (63, 'Scrappy', 'The Pokémon can hit Ghost-type Pokémon with Normal-type and Fighting-type moves.'),
    (64, 'Storm Drain', 'Draws in all Water-type moves to up Sp. Attack.'),
    (65, 'Ice Body', 'The Pokémon regains HP in a hailstorm.'),
    (66, 'Solid Rock', 'Powers down the foe''s super-effective moves.'),
    (67, 'Snow Warning', 'The Pokémon summons a hailstorm in battle.'),
    (68, 'Honey Gather', 'The Pokémon may gather Honey from somewhere.'),
    (69, 'Frisk', 'The Pokémon can check the foe''s held item.'),
    (70, 'Reckless', 'Powers up moves that have recoil damage.'),
    (71, 'Multitype', 'Changes type to match the Plate or Z-Crystal it holds.'),
    (72, 'Flower Gift', 'Powers up the Pokémon and makes it the target of attacks.'),
    (73, 'Bad Dreams', 'Reduces the foe''s HP.'),
    (74, 'Pickpocket', 'Steals an item from the foe when hit.'),
    (75, 'Sheer Force', 'Removes added effects to increase move damage.'),
    (76, 'Contrary', 'Makes stat changes have an opposite effect.'),
    (77, 'Unnerve', 'Unnerves opposing Pokémon and makes them unable to eat Berries.'),
    (78, 'Defiant', 'Boosts the Attack stat when its stats are lowered.'),
    (79, 'Defeatist', 'Halves the Attack and S Attack stats when HP is halved.'),
    (80, 'Cursed Body', 'May disable a move used on the Pokémon.'),
    (81, 'Healer', 'Sometimes heals an ally''s U condition.'),
    (82, 'Friend Guard', 'Reduces damage done to allies.'),
    (83, 'Weak Armor', 'P attacks lower Defense and raise Speed.'),
    (84, 'Heavy Metal', 'Doubles the Pokémon''s weight.'),
    (85, 'Light Metal', 'Halves the Pokémon''s weight.'),
    (86, 'Multiscale', 'Reduces the amount of damage the Pokémon takes when its HP is full.'),
    (87, 'Toxic Boost', 'Powers up P attacks when poisoned.'),
    (88, 'Flare Boost', 'Powers up S attacks when burned.'),
    (89, 'Harvest', 'May create another Berry after one is used.'),
    (90, 'Telepathy', 'Anticipates an ally''s attack and dodges it.')


select * from abilidades

INSERT INTO moves (id_move, nome_move, str_move, acc_move, tipo_move, categoria_move)
VALUES
    (1, 'Pound', 40, 100, 'Normal', 'P'),
    (2, 'Karate Chop', 50, 100, 'Fighting', 'P'),
    (3, 'Double Slap', 15, 85, 'Normal', 'P'),
    (4, 'Comet Punch', 18, 85, 'Normal', 'P'),
    (5, 'Mega Punch', 80, 85, 'Normal', 'P'),
    (6, 'Pay Day', 40, 100, 'Normal', 'P'),
    (7, 'Fire Punch', 75, 100, 'Fire', 'P'),
    (8, 'Ice Punch', 75, 100, 'Ice', 'P'),
    (9, 'Thunder Punch', 75, 100, 'Electric', 'P'),
    (10, 'Scratch', 40, 100, 'Normal', 'P'),
    (11, 'Vice Grip', 55, 100, 'Normal', 'P'),
    (12, 'Guillotine', null, 30, 'Normal', 'P'),
    (13, 'Razor Wind', 80, 75, 'Normal', 'S'),
    (14, 'Swords Dance', null, null, 'Normal', 'U'),
    (15, 'Cut', 50, 95, 'Normal', 'P'),
    (16, 'Gust', 40, 100, 'Flying', 'S'),
    (17, 'Wing Attack', 60, 100, 'Flying', 'P'),
    (18, 'Whirlwind', null, null, 'Normal', 'U'),
    (19, 'Fly', 90, 95, 'Flying', 'P'),
    (20, 'Bind', 15, 85, 'Normal', 'P'),
    (21, 'Slam', 80, 75, 'Normal', 'P'),
    (22, 'Vine Whip', 45, 100, 'Grass', 'P'),
    (23, 'Stomp', 65, 100, 'Normal', 'P'),
    (24, 'Double Kick', 30, 100, 'Fighting', 'P'),
    (25, 'Mega Kick', 120, 75, 'Normal', 'P'),
    (26, 'Jump Kick', 70, 95, 'Fighting', 'P'),
    (27, 'Rolling Kick', 60, 85, 'Fighting', 'P'),
    (28, 'Sand Attack', null, 100, 'Ground', 'U'),
    (29, 'Headbutt', 70, 100, 'Normal', 'P'),
    (30, 'Horn Attack', 65, 100, 'Normal', 'P'),
    (31, 'Fury Attack', 15, 85, 'Normal', 'P'),
    (32, 'Horn Drill', null, 30, 'Normal', 'P'),
    (33, 'Tackle', 40, 100, 'Normal', 'P'),
    (34, 'Body Slam', 85, 100, 'Normal', 'P'),
    (35, 'Wrap', 15, 90, 'Normal', 'P'),
    (36, 'Take Down', 90, 85, 'Normal', 'P'),
    (37, 'Thrash', 120, 100, 'Normal', 'P'),
    (38, 'Double-Edge', 120, 100, 'Normal', 'P'),
    (39, 'Tail Whip', null, 100, 'Normal', 'U'),
    (40, 'Poison Sting', 15, 100, 'Poison', 'P'),
    (41, 'Twineedle', 25, 100, 'Bug', 'P'),
    (42, 'Pin Missile', 14, 85, 'Bug', 'P'),
    (43, 'Leer', null, 100, 'Normal', 'U'),
    (44, 'Bite', 60, 100, 'Dark', 'P'),
    (45, 'Growl', null, 100, 'Normal', 'U'),
    (46, 'Roar', null, 100, 'Normal', 'U'),
    (47, 'Sing', null, 55, 'Normal', 'U'),
    (48, 'Supersonic', null, 55, 'Normal', 'U'),
    (49, 'Sonic Boom', null, 90, 'Normal', 'S'),
    (50, 'Disable', null, 100, 'Normal', 'U'),
    (51, 'Acid', 40, 100, 'Poison', 'S'),
    (52, 'Ember', 40, 100, 'Fire', 'S'),
    (53, 'Flamethrower', 95, 100, 'Fire', 'S'),
    (54, 'Mist', null, null, 'Ice', 'U'),
    (55, 'Water Gun', 40, 100, 'Water', 'S'),
    (56, 'Hydro Pump', 120, 80, 'Water', 'S'),
    (57, 'Surf', 90, 100, 'Water', 'S'),
    (58, 'Ice Beam', 95, 100, 'Ice', 'S'),
    (59, 'Blizzard', 120, 70, 'Ice', 'S'),
    (60, 'Psybeam', 65, 100, 'Psychic', 'S'),
    (61, 'Bubble Beam', 65, 100, 'Water', 'S'),
    (62, 'Aurora Beam', 65, 100, 'Ice', 'S'),
    (63, 'Hyper Beam', 150, 90, 'Normal', 'S'),
    (64, 'Peck', 35, 100, 'Flying', 'P'),
    (65, 'Drill Peck', 80, 100, 'Flying', 'P'),
    (66, 'Submission', 80, 80, 'Fighting', 'P'),
    (67, 'Low Kick', null, 100, 'Fighting', 'P'),
    (68, 'Counter', null, 100, 'Fighting', 'P'),
    (69, 'Seismic Toss', null, 100, 'Fighting', 'P'),
    (70, 'Strength', 80, 100, 'Normal', 'P'),
    (71, 'Absorb', 20, 100, 'Grass', 'S'),
    (72, 'Mega Drain', 40, 100, 'Grass', 'S'),
    (73, 'Leech Seed', null, 90, 'Grass', 'U'),
    (74, 'Growth', null, null, 'Normal', 'U'),
    (75, 'Razor Leaf', 55, 95, 'Grass', 'P'),
    (76, 'Solar Beam', 120, 100, 'Grass', 'S'),
    (77, 'Poison Powder', null, 75, 'Poison', 'U'),
    (78, 'Stun Spore', null, 75, 'Grass', 'U'),
    (79, 'Sleep Powder', null, 75, 'Grass', 'U'),
    (80, 'Petal Dance', 120, 100, 'Grass', 'S'),
    (81, 'String Shot', null, 95, 'Bug', 'U'),
    (82, 'Dragon Rage', null, 100, 'Dragon', 'S'),
    (83, 'Fire Spin', 35, 85, 'Fire', 'S'),
    (84, 'Thunder Shock', 40, 100, 'Electric', 'S'),
    (85, 'Thunderbolt', 90, 100, 'Electric', 'S'),
    (86, 'Thunder Wave', null, 100, 'Electric', 'U'),
    (87, 'Thunder', 120, 70, 'Electric', 'S'),
    (88, 'Rock Throw', 50, 90, 'Rock', 'P'),
    (89, 'Earthquake', 100, 100, 'Ground', 'P'),
    (90, 'Fissure', null, 30, 'Ground', 'P'),
    (91, 'Dig', 80, 100, 'Ground', 'P'),
    (92, 'Toxic', null, 85, 'Poison', 'U'),
    (93, 'Confusion', 50, 100, 'Psychic', 'S'),
    (94, 'Psychic', 90, 100, 'Psychic', 'S'),
    (95, 'Hypnosis', null, 60, 'Psychic', 'U'),
    (96, 'Meditate', null, null, 'Psychic', 'U'),
    (97, 'Agility', null, null, 'Psychic', 'U'),
    (98, 'Quick Attack', 40, 100, 'Normal', 'P'),
    (99, 'Rage', 20, 100, 'Normal', 'P'),
    (100, 'Teleport', null, null, 'Psychic', 'U'),
    (101, 'Night Shade', null, 100, 'Ghost', 'S'),
    (102, 'Mimic', null, 100, 'Normal', 'U'),
    (103, 'Screech', null, 85, 'Normal', 'U'),
    (104, 'Double Team', null, null, 'Normal', 'U'),
    (105, 'Recover', null, null, 'Normal', 'U'),
    (106, 'Harden', null, null, 'Normal', 'U'),
    (107, 'Minimize', null, null, 'Normal', 'U'),
    (108, 'Smokescreen', null, 100, 'Normal', 'U'),
    (109, 'Confuse Ray', null, 100, 'Ghost', 'U'),
    (110, 'Withdraw', null, null, 'Water', 'U'),
    (111, 'Defense Curl', null, null, 'Normal', 'U'),
    (112, 'Barrier', null, null, 'Psychic', 'U'),
    (113, 'Light Screen', null, null, 'Psychic', 'U'),
    (114, 'Haze', null, null, 'Ice', 'U'),
    (115, 'Reflect', null, null, 'Psychic', 'U'),
    (116, 'Focus Energy', null, null, 'Normal', 'U'),
    (117, 'Bide', null, null, 'Normal', 'P'),
    (118, 'Metronome', null, null, 'Normal', 'U'),
    (119, 'Mirror Move', null, null, 'Flying', 'U'),
    (120, 'Self-Destruct', 200, 100, 'Normal', 'P'),
    (121, 'Egg Bomb', 100, 75, 'Normal', 'P'),
    (122, 'Lick', 20, 100, 'Ghost', 'P'),
    (123, 'Smog', 20, 70, 'Poison', 'S'),
    (124, 'Sludge', 65, 100, 'Poison', 'S'),
    (125, 'Bone Club', 65, 85, 'Ground', 'P'),
    (126, 'Fire Blast', 120, 85, 'Fire', 'S'),
    (127, 'Waterfall', 80, 100, 'Water', 'P'),
    (128, 'Clamp', 35, 85, 'Water', 'P'),
    (129, 'Swift', 60, null, 'Normal', 'S'),
    (130, 'Skull Bash', 100, 100, 'Normal', 'P'),
    (131, 'Spike Cannon', 20, 100, 'Normal', 'P'),
    (132, 'Constrict', 10, 100, 'Normal', 'P'),
    (133, 'Amnesia', null, null, 'Psychic', 'U'),
    (134, 'Kinesis', null, 80, 'Psychic', 'U'),
    (135, 'Soft-Boiled', null, null, 'Normal', 'U'),
    (136, 'High Jump Kick', 85, 90, 'Fighting', 'P'),
    (137, 'Glare', null, 90, 'Normal', 'U'),
    (138, 'Dream Eater', 100, 100, 'Psychic', 'S'),
    (139, 'Poison Gas', null, 90, 'Poison', 'U'),
    (140, 'Barrage', 15, 85, 'Normal', 'P'),
    (141, 'Leech Life', 20, 100, 'Bug', 'P'),
    (142, 'Lovely Kiss', null, 75, 'Normal', 'U'),
    (143, 'Sky Attack', 140, 90, 'Flying', 'P'),
    (144, 'Transform', null, null, 'Normal', 'U'),
    (145, 'Bubble', 20, 100, 'Water', 'S'),
    (146, 'Dizzy Punch', 70, 100, 'Normal', 'S'),
    (147, 'Spore', null, 100, 'Grass', 'U'),
    (148, 'Flash', null, 100, 'Normal', 'U'),
    (149, 'Psywave', null, 80, 'Psychic', 'S'),
    (150, 'Splash', null, null, 'Normal', 'U'),
    (151, 'Acid Armor', null, null, 'Poison', 'U'),
    (152, 'Crabhammer', 90, 85, 'Water', 'P'),
    (153, 'Explosion', 250, 100, 'Normal', 'P'),
    (154, 'Fury Swipes', 18, 80, 'Normal', 'P'),
    (155, 'Bonemerang', 50, 90, 'Ground', 'P'),
    (156, 'Rest', null, null, 'Psychic', 'U'),
    (157, 'Rock Slide', 75, 90, 'Rock', 'P'),
    (158, 'Hyper Fang', 80, 90, 'Normal', 'P'),
    (159, 'Sharpen', null, null, 'Normal', 'U'),
    (160, 'Conversion', null, null, 'Normal', 'U'),
    (161, 'Tri Attack', 80, 100, 'Normal', 'S'),
    (162, 'Super Fang', null, 90, 'Normal', 'P'),
    (163, 'Slash', 70, 100, 'Normal', 'P'),
    (164, 'Substitute', null, null, 'Normal', 'U'),
    (165, 'Struggle', 50, null, 'Normal', 'P'),
    (166, 'Sketch', null, null, 'Normal', 'U'),
    (167, 'Triple Kick', 10, 90, 'Fighting', 'P'),
    (168, 'Thief', 60, 100, 'Dark', 'P'),
    (169, 'Spider Web', null, null, 'Bug', 'U'),
    (170, 'Mind Reader', null, null, 'Normal', 'U'),
    (171, 'Nightmare', null, 100, 'Ghost', 'U'),
    (172, 'Flame Wheel', 60, 100, 'Fire', 'P'),
    (173, 'Snore', 40, 100, 'Normal', 'S'),
    (174, 'Curse', null, null, 'Ghost', 'U'),
    (175, 'Flail', null, 100, 'Normal', 'P'),
    (176, 'Conversion 2', null, null, 'Normal', 'U'),
    (177, 'Aeroblast', 100, 95, 'Flying', 'S'),
    (178, 'Cotton Spore', null, 100, 'Grass', 'U'),
    (179, 'Reversal', null, 100, 'Fighting', 'P'),
    (180, 'Spite', null, 100, 'Ghost', 'U'),
    (181, 'Powder Snow', 40, 100, 'Ice', 'S'),
    (182, 'Protect', null, null, 'Normal', 'U'),
    (183, 'Mach Punch', 40, 100, 'Fighting', 'P'),
    (184, 'Scary Face', null, 90, 'Normal', 'U'),
    (185, 'Faint Attack', 60, null, 'Dark', 'P'),
    (186, 'Sweet Kiss', null, 75, 'Normal', 'U'),
    (187, 'Belly Drum', null, null, 'Normal', 'U'),
    (188, 'Sludge Bomb', 90, 100, 'Poison', 'S'),
    (189, 'Mud-Slap', 20, 100, 'Ground', 'S'),
    (190, 'Octazooka', 65, 85, 'Water', 'S'),
    (191, 'Spikes', null, null, 'Ground', 'U'),
    (192, 'Zap Cannon', 100, 50, 'Electric', 'S'),
    (193, 'Foresight', null, null, 'Normal', 'U'),
    (194, 'Destiny Bond', null, null, 'Ghost', 'U'),
    (195, 'Perish Song', null, null, 'Normal', 'U'),
    (196, 'Icy Wind', 55, 95, 'Ice', 'S'),
    (197, 'Detect', null, null, 'Fighting', 'U'),
    (198, 'Bone Rush', 25, 90, 'Ground', 'P'),
    (199, 'Lock-On', null, null, 'Normal', 'U'),
    (200, 'Outrage', 120, 100, 'Dragon', 'P'),
    (201, 'Sandstorm', null, null, 'Rock', 'U'),
    (202, 'Giga Drain', 60, 100, 'Grass', 'S'),
    (203, 'Endure', null, null, 'Normal', 'U'),
    (204, 'Charm', null, 100, 'Fairy', 'U'),
    (205, 'Rollout', 30, 90, 'Rock', 'P'),
    (206, 'False Swipe', 40, 100, 'Normal', 'P'),
    (207, 'Swagger', null, 90, 'Normal', 'U'),
    (208, 'Milk Drink', null, null, 'Normal', 'U'),
    (209, 'Spark', 65, 100, 'Electric', 'P'),
    (210, 'Fury Cutter', 20, 95, 'Bug', 'P'),
    (211, 'Steel Wing', 70, 90, 'Steel', 'P'),
    (212, 'Mean Look', null, null, 'Normal', 'U'),
    (213, 'Attract', null, 100, 'Normal', 'U'),
    (214, 'Sleep Talk', null, null, 'Normal', 'U'),
    (215, 'Heal Bell', null, null, 'Normal', 'U'),
    (216, 'Return', null, 100, 'Normal', 'P'),
    (217, 'Present', null, 90, 'Normal', 'P'),
    (218, 'Frustration', null, 100, 'Normal', 'P'),
    (219, 'Safeguard', null, null, 'Normal', 'U'),
    (220, 'Pain Split', null, null, 'Normal', 'U'),
    (221, 'Sacred Fire', 100, 95, 'Fire', 'P'),
    (222, 'Magnitude', null, 100, 'Ground', 'P'),
    (223, 'Dynamic Punch', 100, 50, 'Fighting', 'P'),
    (224, 'Megahorn', 120, 85, 'Bug', 'P'),
    (225, 'Dragon Breath', 60, 100, 'Dragon', 'S'),
    (226, 'Baton Pass', null, null, 'Normal', 'U'),
    (227, 'Encore', null, 100, 'Normal', 'U'),
    (228, 'Pursuit', 40, 100, 'Dark', 'P'),
    (229, 'Rapid Spin', 20, 100, 'Normal', 'P'),
    (230, 'Sweet Scent', null, 100, 'Normal', 'U'),
    (231, 'Iron Tail', 100, 75, 'Steel', 'P'),
    (232, 'Metal Claw', 50, 95, 'Steel', 'P'),
    (233, 'Vital Throw', 70, null, 'Fighting', 'P'),
    (234, 'Morning Sun', null, null, 'Normal', 'U'),
    (235, 'Synthesis', null, null, 'Grass', 'U'),
    (236, 'Moonlight', null, null, 'Fairy', 'U'),
    (237, 'Hidden Power', null, 100, 'Normal', 'S'),
    (238, 'Cross Chop', 100, 80, 'Fighting', 'P'),
    (239, 'Twister', 40, 100, 'Dragon', 'S'),
    (240, 'Rain Dance', null, null, 'Water', 'U'),
    (241, 'Sunny Day', null, null, 'Fire', 'U'),
    (242, 'Crunch', 80, 100, 'Dark', 'P'),
    (243, 'Mirror Coat', null, 100, 'Psychic', 'S'),
    (244, 'Psych Up', null, null, 'Normal', 'U'),
    (245, 'Extreme Speed', 80, 100, 'Normal', 'P'),
    (246, 'Ancient Power', 60, 100, 'Rock', 'S'),
    (247, 'Shadow Ball', 80, 100, 'Ghost', 'S'),
    (248, 'Future Sight', 120, 100, 'Psychic', 'S'),
    (249, 'Rock Smash', 20, 100, 'Fighting', 'P'),
    (250, 'Whirlpool', 35, 85, 'Water', 'S'),
    (251, 'Beat Up', null, 100, 'Dark', 'P'),
    (252, 'Fake Out', 40, 100, 'Normal', 'P'),
    (253, 'Uproar', 50, 100, 'Normal', 'S'),
    (254, 'Stockpile', null, null, 'Normal', 'U'),
    (255, 'Spit Up', null, 100, 'Normal', 'S'),
    (256, 'Swallow', null, null, 'Normal', 'U'),
    (257, 'Heat Wave', 95, 90, 'Fire', 'S'),
    (258, 'Hail', null, null, 'Ice', 'U'),
    (259, 'Torment', null, 100, 'Dark', 'U'),
    (260, 'Flatter', null, 100, 'Dark', 'U'),
    (261, 'Will-O-Wisp', null, 85, 'Fire', 'U'),
    (262, 'Memento', null, 100, 'Dark', 'U'),
    (263, 'Facade', 70, 100, 'Normal', 'P'),
    (264, 'Focus Punch', 150, 100, 'Fighting', 'P'),
    (265, 'Smelling Salts', 60, 100, 'Normal', 'P'),
    (266, 'Follow Me', null, null, 'Normal', 'U'),
    (267, 'Nature Power', null, null, 'Normal', 'U'),
    (268, 'Charge', null, null, 'Electric', 'U'),
    (269, 'Taunt', null, 100, 'Dark', 'U'),
    (270, 'Helping Hand', null, null, 'Normal', 'U'),
    (271, 'Trick', null, 100, 'Psychic', 'U'),
    (272, 'Role Play', null, null, 'Psychic', 'U'),
    (273, 'Wish', null, null, 'Normal', 'U'),
    (274, 'Assist', null, null, 'Normal', 'U'),
    (275, 'Ingrain', null, null, 'Grass', 'U'),
    (276, 'Superpower', 120, 100, 'Fighting', 'P'),
    (277, 'Magic Coat', null, null, 'Psychic', 'U'),
    (278, 'Recycle', null, null, 'Normal', 'U'),
    (279, 'Revenge', 60, 100, 'Fighting', 'P'),
    (280, 'Brick Break', 75, 100, 'Fighting', 'P'),
    (281, 'Yawn', null, null, 'Normal', 'U'),
    (282, 'Knock Off', 65, 100, 'Dark', 'P'),
    (283, 'Endeavor', null, 100, 'Normal', 'P'),
    (284, 'Eruption', 150, 100, 'Fire', 'S'),
    (285, 'Skill Swap', null, null, 'Psychic', 'U'),
    (286, 'Imprison', null, null, 'Psychic', 'U'),
    (287, 'Refresh', null, null, 'Normal', 'U'),
    (288, 'Grudge', null, null, 'Ghost', 'U'),
    (289, 'Snatch', null, null, 'Dark', 'U'),
    (290, 'Secret Power', 70, 100, 'Normal', 'P'),
    (291, 'Dive', 80, 100, 'Water', 'P'),
    (292, 'Arm Thrust', 15, 100, 'Fighting', 'P'),
    (293, 'Camouflage', null, null, 'Normal', 'U'),
    (294, 'Tail Glow', null, null, 'Bug', 'U'),
    (295, 'Luster Purge', 70, 100, 'Psychic', 'S'),
    (296, 'Mist Ball', 70, 100, 'Psychic', 'S'),
    (297, 'Feather Dance', null, 100, 'Flying', 'U'),
    (298, 'Teeter Dance', null, 100, 'Normal', 'U'),
    (299, 'Blaze Kick', 85, 90, 'Fire', 'P'),
    (300, 'Mud Sport', null, null, 'Ground', 'U'),
    (301, 'Ice Ball', 30, 90, 'Ice', 'P'),
    (302, 'Needle Arm', 60, 100, 'Grass', 'P'),
    (303, 'Slack Off', null, null, 'Normal', 'U'),
    (304, 'Hyper Voice', 90, 100, 'Normal', 'S'),
    (305, 'Poison Fang', 50, 100, 'Poison', 'P'),
    (306, 'Crush Claw', 75, 95, 'Normal', 'P'),
    (307, 'Blast Burn', 150, 90, 'Fire', 'S'),
    (308, 'Hydro Cannon', 150, 90, 'Water', 'S'),
    (309, 'Meteor Mash', 100, 85, 'Steel', 'P'),
    (310, 'Astonish', 30, 100, 'Ghost', 'P'),
    (311, 'Weather Ball', 50, 100, 'Normal', 'S'),
    (312, 'Aromatherapy', null, null, 'Grass', 'U'),
    (313, 'Fake Tears', null, 100, 'Dark', 'U'),
    (314, 'Air Cutter', 60, 95, 'Flying', 'S'),
    (315, 'Overheat', 130, 90, 'Fire', 'S'),
    (316, 'Odor Sleuth', null, null, 'Normal', 'U'),
    (317, 'Rock Tomb', 60, 95, 'Rock', 'P'),
    (318, 'Silver Wind', 60, 100, 'Bug', 'S'),
    (319, 'Metal Sound', null, 85, 'Steel', 'U'),
    (320, 'Grass Whistle', null, 55, 'Grass', 'U'),
    (321, 'Tickle', null, 100, 'Normal', 'U'),
    (322, 'Cosmic Power', null, null, 'Psychic', 'U'),
    (323, 'Water Spout', 150, 100, 'Water', 'S'),
    (324, 'Signal Beam', 75, 100, 'Bug', 'S'),
    (325, 'Shadow Punch', 60, null, 'Ghost', 'P'),
    (326, 'Extrasensory', 80, 100, 'Psychic', 'S'),
    (327, 'Sky Uppercut', 85, 90, 'Fighting', 'P'),
    (328, 'Sand Tomb', 35, 85, 'Ground', 'P'),
    (329, 'Sheer Cold', null, 30, 'Ice', 'S'),
    (330, 'Muddy Water', 90, 85, 'Water', 'S'),
    (331, 'Bullet Seed', 25, 100, 'Grass', 'P'),
    (332, 'Aerial Ace', 60, null, 'Flying', 'P'),
    (333, 'Icicle Spear', 25, 100, 'Ice', 'P'),
    (334, 'Iron Defense', null, null, 'Steel', 'U'),
    (335, 'Block', null, 100, 'Normal', 'U'),
    (336, 'Howl', null, null, 'Normal', 'U'),
    (337, 'Dragon Claw', 80, 100, 'Dragon', 'P'),
    (338, 'Frenzy Plant', 150, 90, 'Grass', 'S'),
    (339, 'Bulk Up', null, null, 'Fighting', 'U'),
    (340, 'Bounce', 85, 85, 'Flying', 'P'),
    (341, 'Mud Shot', 55, 95, 'Ground', 'S'),
    (342, 'Poison Tail', 50, 100, 'Poison', 'P'),
    (343, 'Covet', 60, 100, 'Normal', 'P'),
    (344, 'Volt Tackle', 120, 100, 'Electric', 'P'),
    (345, 'Magical Leaf', 60, null, 'Grass', 'S'),
    (346, 'Water Sport', null, null, 'Water', 'U'),
    (347, 'Calm Mind', null, null, 'Psychic', 'U'),
    (348, 'Leaf Blade', 90, 100, 'Grass', 'P'),
    (349, 'Dragon Dance', null, null, 'Dragon', 'U'),
    (350, 'Rock Blast', 25, 90, 'Rock', 'P'),
    (351, 'Shock Wave', 60, null, 'Electric', 'S'),
    (352, 'Water Pulse', 60, 100, 'Water', 'S'),
    (353, 'Doom Desire', 140, 100, 'Steel', 'S'),
    (354, 'Psycho Boost', 140, 90, 'Psychic', 'S'),
    (355, 'Roost', null, null, 'Flying', 'U'),
    (356, 'Gravity', null, null, 'Psychic', 'U'),
    (357, 'Miracle Eye', null, 100, 'Psychic', 'U'),
    (358, 'Wake-Up Slap', 70, 100, 'Fighting', 'P'),
    (359, 'Hammer Arm', 100, 90, 'Fighting', 'P'),
    (360, 'Gyro Ball', null, 100, 'Steel', 'P'),
    (361, 'Healing Wish', null, null, 'Psychic', 'U'),
    (362, 'Brine', 65, 100, 'Water', 'S'),
    (363, 'Natural Gift', null, 100, 'Normal', 'P'),
    (364, 'Feint', 30, 100, 'Normal', 'P'),
    (365, 'Pluck', 60, 100, 'Flying', 'P'),
    (366, 'Tailwind', null, null, 'Flying', 'U'),
    (367, 'Acupressure', null, null, 'Normal', 'U'),
    (368, 'Metal Burst', null, 100, 'Steel', 'P'),
    (369, 'U-turn', 70, 100, 'Bug', 'P'),
    (370, 'Close Combat', 120, 100, 'Fighting', 'P'),
    (371, 'Payback', 50, 100, 'Dark', 'P'),
    (372, 'Assurance', 60, 100, 'Dark', 'P'),
    (373, 'Embargo', null, 100, 'Dark', 'U'),
    (374, 'Fling', null, 100, 'Dark', 'P'),
    (375, 'Psycho Shift', null, 90, 'Psychic', 'U'),
    (376, 'Trump Card', null, null, 'Normal', 'S'),
    (377, 'Heal Block', null, 100, 'Psychic', 'U'),
    (378, 'Wring Out', null, 100, 'Normal', 'S'),
    (379, 'Power Trick', null, null, 'Psychic', 'U'),
    (380, 'Gastro Acid', null, 100, 'Poison', 'U'),
    (381, 'Lucky Chant', null, null, 'Normal', 'U'),
    (382, 'Me First', null, null, 'Normal', 'U'),
    (383, 'Copycat', null, null, 'Normal', 'U'),
    (384, 'Power Swap', null, null, 'Psychic', 'U'),
    (385, 'Guard Swap', null, null, 'Psychic', 'U'),
    (386, 'Punishment', null, 100, 'Dark', 'P'),
    (387, 'Last Resort', 140, 100, 'Normal', 'P'),
    (388, 'Worry Seed', null, 100, 'Grass', 'U'),
    (389, 'Sucker Punch', 70, 100, 'Dark', 'P'),
    (390, 'Toxic Spikes', null, null, 'Poison', 'U'),
    (391, 'Heart Swap', null, null, 'Psychic', 'U'),
    (392, 'Aqua Ring', null, null, 'Water', 'U'),
    (393, 'Magnet Rise', null, null, 'Electric', 'U'),
    (394, 'Flare Blitz', 120, 100, 'Fire', 'P'),
    (395, 'Force Palm', 60, 100, 'Fighting', 'P'),
    (396, 'Aura Sphere', 80, null, 'Fighting', 'S'),
    (397, 'Rock Polish', null, null, 'Rock', 'U'),
    (398, 'Poison Jab', 80, 100, 'Poison', 'P'),
    (399, 'Dark Pulse', 80, 100, 'Dark', 'S'),
    (400, 'Night Slash', 70, 100, 'Dark', 'P'),
    (401, 'Aqua Tail', 90, 90, 'Water', 'P'),
    (402, 'Seed Bomb', 80, 100, 'Grass', 'P'),
    (403, 'Air Slash', 75, 95, 'Flying', 'S'),
    (404, 'X-Scissor', 80, 100, 'Bug', 'P'),
    (405, 'Bug Buzz', 90, 100, 'Bug', 'S'),
    (406, 'Dragon Pulse', 85, 100, 'Dragon', 'S'),
    (407, 'Dragon Rush', 100, 75, 'Dragon', 'P'),
    (408, 'Power Gem', 80, 100, 'Rock', 'S'),
    (409, 'Drain Punch', 75, 100, 'Fighting', 'P'),
    (410, 'Vacuum Wave', 40, 100, 'Fighting', 'S'),
    (411, 'Focus Blast', 120, 70, 'Fighting', 'S'),
    (412, 'Energy Ball', 90, 100, 'Grass', 'S'),
    (413, 'Brave Bird', 120, 100, 'Flying', 'P'),
    (414, 'Earth Power', 90, 100, 'Ground', 'S'),
    (415, 'Switcheroo', null, 100, 'Dark', 'U'),
    (416, 'Giga Impact', 150, 90, 'Normal', 'P'),
    (417, 'Nasty Plot', null, null, 'Dark', 'U'),
    (418, 'Bullet Punch', 40, 100, 'Steel', 'P'),
    (419, 'Avalanche', 60, 100, 'Ice', 'P'),
    (420, 'Ice Shard', 40, 100, 'Ice', 'P'),
    (421, 'Shadow Claw', 70, 100, 'Ghost', 'P'),
    (422, 'Thunder Fang', 65, 95, 'Electric', 'P'),
    (423, 'Ice Fang', 65, 95, 'Ice', 'P'),
    (424, 'Fire Fang', 65, 95, 'Fire', 'P'),
    (425, 'Shadow Sneak', 40, 100, 'Ghost', 'P'),
    (426, 'Mud Bomb', 65, 85, 'Ground', 'S'),
    (427, 'Psycho Cut', 70, 100, 'Psychic', 'P'),
    (428, 'Zen Headbutt', 80, 90, 'Psychic', 'P'),
    (429, 'Mirror Shot', 65, 85, 'Steel', 'S'),
    (430, 'Flash Cannon', 80, 100, 'Steel', 'S'),
    (431, 'Rock Climb', 90, 85, 'Normal', 'P'),
    (432, 'Defend Order', null, null, 'Bug', 'U'),
    (433, 'Heal Order', null, null, 'Bug', 'U'),
    (434, 'Head Smash', 150, 80, 'Rock', 'P'),
    (435, 'Double Hit', 35, 90, 'Normal', 'P'),
    (436, 'Roar of Time', 150, 90, 'Dragon', 'S'),
    (437, 'Spacial Rend', 100, 95, 'Dragon', 'S'),
    (438, 'Lunar Dance', null, null, 'Psychic', 'U'),
    (439, 'Crush Grip', null, 100, 'Normal', 'P'),
    (440, 'Magma Storm', 100, 75, 'Fire', 'S'),
    (441, 'Dark Void', null, 50, 'Dark', 'U'),
    (442, 'Seed Flare', 120, 85, 'Grass', 'S'),
    (443, 'Ominous Wind', 60, 100, 'Ghost', 'S'),
    (444, 'Shadow Force', 120, 100, 'Ghost', 'P'),
    (445, 'Hone Claws', null, null, 'Dark', 'U'),
    (446, 'Wide Guard', null, null, 'Rock', 'U'),
    (447, 'Guard Split', null, null, 'Psychic', 'U'),
    (448, 'Power Split', null, null, 'Psychic', 'U'),
    (449, 'Wonder Room', null, null, 'Psychic', 'U'),
    (450, 'Psyshock', 80, 100, 'Psychic', 'S'),
    (451, 'Venoshock', 65, 100, 'Poison', 'S'),
    (452, 'Autotomize', null, null, 'Steel', 'U'),
    (453, 'Rage Powder', null, null, 'Bug', 'U'),
    (454, 'Telekinesis', null, null, 'Psychic', 'U'),
    (455, 'Magic Room', null, null, 'Psychic', 'U'),
    (456, 'Smack Down', 50, 100, 'Rock', 'P'),
    (457, 'Storm Throw', 60, 100, 'Fighting', 'P'),
    (458, 'Flame Burst', 70, 100, 'Fire', 'S'),
    (459, 'Sludge Wave', 95, 100, 'Poison', 'S'),
    (460, 'Quiver Dance', null, null, 'Bug', 'U'),
    (461, 'Heavy Slam', null, 100, 'Steel', 'P')

	select * from moves
	
INSERT INTO pokemon_data (id_data, nome_pokemon, descricao_pokemon, imagem_pokemon, icone_pokemon, tipo1_pokemon, tipo2_pokemon)
VALUES (2, 'Charmander', 'A fire type Pokémon', 'charmander.png', 'charmander_icon.png', 'Fire', NULL);

INSERT INTO pokemon_abilities (id_pokemon, id_ability)
VALUES (2, 4); 

INSERT INTO pokemon_data (id_data, nome_pokemon, descricao_pokemon, imagem_pokemon, icone_pokemon, tipo1_pokemon, tipo2_pokemon)
VALUES (3, 'Charmeleon', 'A fire type Pokémon', 'charmeleon.png', 'charmeleon_icon.png', 'Fire', NULL);

INSERT INTO pokemon_abilities (id_pokemon, id_ability)
VALUES (3, 4); 

INSERT INTO pokemon_data (id_data, nome_pokemon, descricao_pokemon, imagem_pokemon, icone_pokemon, tipo1_pokemon, tipo2_pokemon)
VALUES (4, 'Charizard', 'A fire-flying type Pokémon', 'charizard.png', 'charizard_icon.png', 'Fire', 'Flying');


INSERT INTO pokemon_abilities (id_pokemon, id_ability)
VALUES (4, 4); 



INSERT INTO pokemon_moves (id_pokemon, id_move)
VALUES (4, 4);  

INSERT INTO pokemon_moves (id_pokemon, id_move)
VALUES (4, 5); 

INSERT INTO pokemon_moves (id_pokemon, id_move)
VALUES (4, 6); 

select * from pokemon_data